"""empty message

Revision ID: 99cf8cd1f8de
Revises: 
Create Date: 2024-06-24 00:59:36.196187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99cf8cd1f8de'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consume',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('picture', sa.Integer(), nullable=True),
    sa.Column('base', sa.String(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['picture'], ['picture.id'], ),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consume_id'), 'consume', ['id'], unique=False)
    op.create_table('print_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('picture', sa.Integer(), nullable=True),
    sa.Column('printer', sa.String(), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('log_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['picture'], ['picture.id'], ),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_print_log_id'), 'print_log', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_print_log_id'), table_name='print_log')
    op.drop_table('print_log')
    op.drop_index(op.f('ix_consume_id'), table_name='consume')
    op.drop_table('consume')
    # ### end Alembic commands ###
